apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ton3s
build:
  artifacts:
    - image: ton3s-backend
      context: ./backend
      docker:
        dockerfile: Dockerfile
    - image: ton3s-frontend
      context: ./frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
      - name: ton3s
        chartPath: ./k8s
        namespace: ton3s
        createNamespace: true
